[project]
name = "comfyui-otacoo"
description = "A set of nodes for loading checkpoints and LoRAs with model image previews. Also includes a node to set samplers & schedulers globally."
version = "1.3.2"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/otacoo/comfyui-otacoo"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "otacoo"
DisplayName = "comfyui-otacoo"
Icon = "https://avatars.githubusercontent.com/u/208893667"
